// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Expired CC (Allied Health Provider)', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Expired CC (Allied Health Provider)', async function() {
    await driver.get("https://eishealth--dev--c.cs115.visual.force.com/apex/MembershipSignUp")
    await driver.findElement(By.id("type")).click()
    {
      const dropdown = await driver.findElement(By.id("type"))
      await dropdown.findElement(By.css("*[value='Allied Health Provider - Medicare Approved']")).click()
    }
    await driver.findElement(By.id("membershipPostcode")).click()
    await driver.findElement(By.id("membershipPostcode")).sendKeys("123355677899")
    await driver.findElement(By.id("firstName")).sendKeys("Selenium")
    await driver.findElement(By.id("lastName")).sendKeys("Test")
    await driver.findElement(By.id("email")).sendKeys("developer+selenium@vertic.com.au")
    await driver.findElement(By.id("category")).click()
    {
      const dropdown = await driver.findElement(By.id("category"))
      await dropdown.findElement(By.css("*[value='Dentist']")).click()
    }
    await driver.findElement(By.id("product")).click()
    {
      const dropdown = await driver.findElement(By.id("product"))
      await dropdown.findElement(By.xpath("//option[. = 'Default Product']")).click()
    }
    await driver.findElement(By.id("gender")).click()
    {
      const dropdown = await driver.findElement(By.id("gender"))
      await dropdown.findElement(By.css("*[value='Male']")).click()
    }
    await driver.findElement(By.css(".row:nth-child(6) .ng-scope > .form-control")).click()
    await driver.findElement(By.xpath("//group-input/input")).sendKeys("Selenium")
    await driver.findElement(By.id("mobilePhone")).sendKeys("1237329204")
    await driver.findElement(By.css(".c-google-address-autocomplete > #address")).sendKeys("ggd")
    await driver.findElement(By.id("mailingStreet")).sendKeys("ggd")
    await driver.findElement(By.id("mailingCity")).sendKeys("mel")
    await driver.findElement(By.id("mailingState")).sendKeys("NT")
    await driver.findElement(By.id("mailingPostalCode")).sendKeys("193847383036")
    await driver.findElement(By.id("mobilePhone")).sendKeys("1237329204")
    await driver.findElement(By.css(".row:nth-child(6) > .col-sm-6:nth-child(1)")).click()
    await driver.findElement(By.id("cardNumber")).click()
    await driver.findElement(By.id("cardNumber")).sendKeys("4444 3333 2222 1111")
    await driver.findElement(By.id("customerName")).click()
    await driver.findElement(By.id("customerName")).sendKeys("selenium")
    await driver.findElement(By.id("Expiry Month")).click()
    {
      const dropdown = await driver.findElement(By.id("Expiry Month"))
      await dropdown.findElement(By.css("*[value='01']")).click()
    }
    await driver.findElement(By.id("Expiry Year")).click()
    {
      const dropdown = await driver.findElement(By.id("Expiry Year"))
      await dropdown.findElement(By.css("*[value='2019']")).click()
    }
    await driver.findElement(By.id("CVN")).click()
    await driver.findElement(By.id("CVN")).sendKeys("123")
    await driver.findElement(By.css(".rsform-submit-button")).click()
    console.log("`set speed` is a no-op in code export, use `pause` instead")
    await driver.wait(until.elementLocated(By.css(".toast-error")), 20000)
    console.log("`set speed` is a no-op in code export, use `pause` instead")
  })
})
