// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Practices', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Practices', async function() {
    await driver.get("https://dev-cesphn.cs115.force.com/apex/servicedirectory")
    await driver.findElement(By.id("Type")).click()
    {
      const dropdown = await driver.findElement(By.id("Type"))
      await dropdown.findElement(By.css("*[value='Practices']")).click()
    }
    await driver.findElement(By.id("Professional Type")).click()
    {
      const dropdown = await driver.findElement(By.id("Professional Type"))
      await dropdown.findElement(By.css("*[value='Allied Health']")).click()
    }
    await driver.findElement(By.id("Location")).click()
    await driver.findElement(By.id("Location")).sendKeys("2350")
    await driver.findElement(By.css(".btn-cy2an")).click()
    await driver.wait(until.elementLocated(By.css(".row:nth-child(4)")), 20000)
  })
})
